name: Build and publish report
on:
  push:
    branches: [ main ]
  workflow_dispatch:

concurrency:
  group: "pages"
  cancel-in-progress: false

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  buildandpublishreport:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Run test cases in container
        run: docker run -e REPORTFILE=/app/tests/index.html -v ${{ github.workspace }}/tests:/app/tests dwupublic/schema-compatibility:v1
      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ${{ github.workspace }}/tests
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
